name: Keep Alive

on:
  schedule:
    - cron: '0 8 1 * *' # Il primo di ogni mese alle 8:00 UTC
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Keep workflows alive
        uses: gautamkrishnar/keepalive-workflow@v2
